[theme]

# primary accent color for interactive elements
primaryColor = "#008B8B"

# Background colour for the main accent area
backgroundColor = "#002b36"

# background colour used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#586e75"

# colour used for almost all text
textColor = "#fff"


